Visitor can see different products on a restaurants menu
CraftAcademy/slowfood-june-2019_team-1 pull request #3
Opened 2019-09-30 17:57 UTC by yasmineezequiel

[PT-link](https://www.pivotaltracker.com/story/show/168829429)
Yasmine & Pia

#PR contains
In this PR we've created a menu index-page where we display different dishes from a restaurants menu. 

## This PR contains
- Feature-test
- Menu controller
- Menu index page
- List with content on menu index page

## What I've learned
- Learned how to convert code in .erb into .haml
- Deeper understanding of working with BDD. 

<img width="1440" alt="Screenshot 2019-09-30 at 19 51 43" src="https://user-images.githubusercontent.com/52795566/65902951-c8dfa400-e3bb-11e9-9abe-2fad222cfb3c.png">

![20190930_135343_001](https://user-images.githubusercontent.com/52795566/65902860-97ff6f00-e3bb-11e9-9bf5-4cb9b5bc6c45.jpg)

2019-09-30 20:42 UTC, faraznaeem requested changes
This feature seems incomplete, the story states that we should see products on the resturants menu. However, this feature only has hardcoded information on the landing page. Please add the Product model and review this feature again to meet the requirements of the story.

2019-09-30 20:42 UTC, faraznaeem commented on config/routes.rb
> +root 'menu#index'
Please use the proper syntax when writing routes, and make sure that you use resourceful routing.

2019-10-01 08:46 UTC, clalil approved these changes

2019-10-01 08:47 UTC, clalil requested changes
- Remove all br
- Change hash in basic_steps to product.

2019-10-01 08:48 UTC, clalil approved these changes

2019-10-01 08:48 UTC, DIzosimov approved these changes

2019-10-01 08:48 UTC, jonas-masharqa approved these changes
Looks good!

2019-10-01 08:49 UTC, piavW approved these changes

2019-10-01 08:50 UTC, jonas-masharqa approved these changes

2019-10-01 08:51 UTC, jonas-masharqa approved these changes

2019-10-01 10:25 UTC, faraznaeem requested changes

2019-10-01 10:25 UTC, faraznaeem commented on app/models/product.rb
> +  validates :price, presence: true
Refactor the validations

2019-10-01 10:25 UTC, faraznaeem commented on config/routes.rb
> +  get 'menu/index'
as we say in swedish: aja baja

2019-10-01 10:25 UTC, faraznaeem commented on features/support/menu.feature
> +    And I should see "garlic bread"
You should test all of the products and their attributes in the background and not only garlic bread

2019-10-01 12:14 UTC, oliverochman commented on features/basic_steps.rb
> +Then("I should see {string}") do |string|
this is an assertion, please put it in an assertion_steps file

2019-10-01 12:14 UTC, oliverochman commented on features/support/menu.feature
> +As a visitor
line 2 to 4 should be indented

2019-10-01 12:14 UTC, oliverochman commented on db/seeds.rb
> +product = Product.create(name: "Garlic Bread", description: "garlic, bread, butter", price: 30)
products = [
  Product.create(name: "Garlic Bread", description: "garlic, bread, butter", price: 30) ,
  Product.create(name: "Margherita", description: "cheese, tomato sauce, basil", price: 70),
  Product.create(name: "Vesuvio", description: "cheese, tomato sauce, ham", price: 70),
  Product.create(name: "Calzone", description: "cheese, tomato sauce, ham", price: 80),
  Product.create(name: "Ice-cream", description: "vanilla", price: 40),
  Product.create(name: "Ice-cream", description: "strawberry", price: 40)
]

2019-10-01 12:23 UTC, oliverochman approved these changes
lgtm!

2019-10-01 12:23 UTC, merged