Visitor can see products sorted in different categories
CraftAcademy/slowfood-june-2019_team-1 pull request #7
Opened 2019-10-02 15:10 UTC by piavW

[PT-link](https://www.pivotaltracker.com/story/show/168829430)
By: Pia & Yasmine
## PR content
In this PR we've sorted the restaurants products into three different categories: Starters, Main Courses, Desserts.

## This PR contains
- Category model
- Unit testing for model
- Feature testing for view of categories
- Association between different models (categories has many products)

## What we've learned
- How to do association with Rails

<img width="1440" alt="Screenshot 2019-10-02 at 17 05 49" src="https://user-images.githubusercontent.com/53825385/66056289-319f5b80-e537-11e9-8a36-0d28abb77f3f.png">

![20190930_135343_001 (1)](https://user-images.githubusercontent.com/53825385/66056272-2c421100-e537-11e9-8445-39cda64bfb48.jpg)

2019-10-02 15:23 UTC, clalil commented on features/category.feature
> + As a visitor,
Indentation please. :)

2019-10-02 15:24 UTC, clalil commented on features/step_definitions/basic_steps.rb
> +Given("I click {string}")do |element|
Space please!

2019-10-02 15:24 UTC, clalil commented on features/step_definitions/basic_steps.rb
> +    fill_in field, with: content
Indentation.

2019-10-02 15:25 UTC, clalil commented on features/step_definitions/basic_steps.rb
> +# Given("The following cars exist") do |table|
Remove, commented lines, please.

2019-10-03 07:31 UTC, oliverochman requested changes

2019-10-03 07:31 UTC, oliverochman commented on config/routes.rb
> +  resources :category
do you need the category routes?

2019-10-03 07:31 UTC, oliverochman commented on features/category.feature
> +    Given the following products exists
`And the following products exists`

2019-10-03 07:31 UTC, oliverochman commented on features/category.feature
> +    Given I visit the landing page
`And I visit the landing page`

2019-10-03 07:31 UTC, oliverochman commented on features/category.feature
> +    Then I should see 'Menu'
Unnecessary assertion, please remove it

2019-10-03 07:31 UTC, oliverochman commented on spec/models/category_spec.rb
> +
you need to test the association between category and product in both model specs

2019-10-03 07:31 UTC, oliverochman commented on app/controllers/products_controller.rb
>      @products = Product.all
do you need this variable now?

2019-10-03 07:57 UTC, clalil approved these changes

2019-10-03 07:58 UTC, yasmineezequiel approved these changes
Awesome!

2019-10-03 08:10 UTC, oliverochman requested changes

2019-10-03 08:10 UTC, oliverochman commented on app/controllers/products_controller.rb
> +    # @products = Product.all
please remove commented out code

2019-10-03 08:10 UTC, oliverochman commented on config/routes.rb
> +  # resources :category
please remove commented out code

2019-10-03 08:10 UTC, oliverochman commented on spec/models/category_spec.rb
> +    it { should have_many( :products) }
please put this in its own description block

```
 describe 'Associations' do
    it { should have_many( :products) }
end

2019-10-03 08:10 UTC, oliverochman commented on spec/models/product_spec.rb
> +    it { should belong_to( :category) }
same here

2019-10-03 08:17 UTC, oliverochman approved these changes

2019-10-03 08:17 UTC, merged